spring.application.name=videochat
spring.config.import=optional:file:.env[.properties]

# Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/videochat
spring.datasource.JWT_KEY=${JWT_KEY}
spring.datasource.username=videochat
spring.datasource.password=pass

# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=create-drop
